2020-02-29 00:11:26 database: wrong user or password; user: "MEAD"
org.h2.message.DbException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:126)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at net.sourceforge.squirrel_sql.fw.sql.SQLDriverManager.getConnection(SQLDriverManager.java:133)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.executeConnect(OpenConnectionCommand.java:167)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand.access$000(OpenConnectionCommand.java:45)
	at net.sourceforge.squirrel_sql.client.mainframe.action.OpenConnectionCommand$1.run(OpenConnectionCommand.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Wrong user name or password [28000-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	... 21 more
2020-03-01 13:04:03 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:08:14 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:08:14 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:08:22 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:08:22 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:27 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:27 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:31 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:31 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:34 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:34 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:35 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:35 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:43 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:49 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:53 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:09:53 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:10:10 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:10:10 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:10:13 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
2020-03-01 13:10:13 jdbc[15]: exception
org.h2.jdbc.JdbcSQLNonTransientException: The object is already closed [90007-199]
